### ISSUE TITLE
OlxOfferTest.offerWithNoPhoto() can time out

### ISSUE THREAD

**Issue by zaza** [zaza/olx-rss#11]
Timed out twice already:

- https://travis-ci.org/zaza/olx-rss/builds/252949876
- https://travis-ci.org/zaza/olx-rss/builds/261608463

'	offerWithNoPhoto(com.github.zaza.olx.OlxOfferTest)  Time elapsed: 14.197 sec  <<< ERROR!

	java.net.SocketTimeoutException: Read timed out

	at java.net.SocketInputStream.socketRead0(Native Method)

	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)

	at java.net.SocketInputStream.read(SocketInputStream.java:171)

	at java.net.SocketInputStream.read(SocketInputStream.java:141)

	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)

	at sun.security.ssl.InputRecord.read(InputRecord.java:503)

	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)

	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)

	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)

	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)

	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)

	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)

	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)

	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)

	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)

	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)

	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)

	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:655)

	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:628)

	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:260)

	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:249)

	at org.jsoup.Jsoup.parse(Jsoup.java:183)

	at com.github.zaza.olx.OlxScrapper.getDocument(OlxScrapper.java:88)

	at com.github.zaza.olx.OlxScrapper.getNextPageElements(OlxScrapper.java:81)

	at com.github.zaza.olx.OlxScrapper.getNextPageUrl(OlxScrapper.java:76)

	at com.github.zaza.olx.OlxScrapper.getOffers(OlxScrapper.java:58)

	at com.github.zaza.olx.OlxOfferTest.offerWithNoPhoto(OlxOfferTest.java:100)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)

	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)

	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)

	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)

	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)

	at org.junit.rules.RunRules.evaluate(RunRules.java:20)

	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)

	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)

	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)

	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)

	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)

	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)

	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)

	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)

	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)

	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)

	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:498)

	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)

	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)

	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)

	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)

	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)'

**Comment by zaza** [comment]
Should be fixed by https://github.com/zaza/olx-rss/issues/10

**Comment by zaza** [comment]
Happened again today: https://travis-ci.org/zaza/olx-rss/builds/476118812

**Comment by zaza** [comment]
Closing as it hasn't happened since September (for almost half a year).
