### ISSUE TITLE
Upgrading jsoup breaks tests

### ISSUE THREAD

**Issue by zaza** [zaza/olx-rss#17]
upgrading jsoup to 1.10.3 causes some tests to fail with:

`org.jsoup.select.Selector$SelectorParseException: Did not find balanced maker at class=link pageNextPrev {page:2}
	at org.jsoup.select.QueryParser.parse(QueryParser.java:44)
	at org.jsoup.select.Selector.<init>(Selector.java:86)
	at org.jsoup.select.Selector.select(Selector.java:108)
	at org.jsoup.nodes.Element.select(Element.java:322)
	at com.github.zaza.olx.OlxScrapper.getNextPageElements(OlxScrapper.java:91)
	at com.github.zaza.olx.OlxScrapper.hasNextPage(OlxScrapper.java:81)
	at com.github.zaza.olx.OlxScrapper.getOffers(OlxScrapper.java:58)
	at com.github.zaza.olx.OlxScrapperTest.assertHasOffers(OlxScrapperTest.java:46)
	at com.github.zaza.olx.OlxScrapperTest.hasOffers(OlxScrapperTest.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
`

**Comment by zaza** [comment]
Fixed by https://github.com/zaza/olx-rss/commit/cec31b52e411c9a2ee2526f7d6edd0a86c65c489, the commit comment incorrectly states it fixes #5
